stages:
  - test
  - build
  - deploy

before_script:
  - echo "Hello World !"
 
test:
  stage: test
  script:
    - echo "Testing..."

build:
  stage: build
  script:
    - echo "Building..."
  artifacts:
    paths:
      - index.html

deploy:
  stage: deploy
  tags:
    - jabba
  environment:
    name: staging
    url: http://62.210.104.135/gitlab/
  dependencies:
    - build
  script:
    - rsync -avz index.html /var/www/html/gitlab/
  only:
    - master